### ISSUE TITLE
Run GM12878/GM18502 data on pBAM pipeline

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/corpora-data-portal#183]
First step towards evaluating the pBAM software as a viable solution to managed access data. Running the pipeline for data on a cell line with a well-characterized genome will help evaluate if it truly masks the identify of the donor.

- [x] Get data from GEO/SRA
- [ ] Get Optimus running in-house
- [ ] Process GM12878/GM18502 dataset
- [ ] Process GM12878/GM18502 dataset w/ pBAM
- [ ] Compare outputs of the 2 processes

**Comment by jychien** [comment]
**Details of Dataset:** GM12878-GM18502 MIXTURE
- Publication: https://www.nature.com/articles/s41597-019-0116-4#Sec12
- Assay: 10x 3' v2
- BioProject: PRJNA508890
- SRA accession ID: SRP172838
- SRA: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8437610
- GEO: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126321

**Tasks that have been done:**
- Converted SRA data into fastq format
- Fastq files for Read1 and Read2 were both 150 bp. The fastqs were clipped using Cutadapt to the following lengths:
    - Read1: 26 bp (cell barcode + UMI)
    - Read2: 96 bp (according to publication, the length of cDNA insert)
