### ISSUE TITLE
pBAM: SingleCellLiverLandscape (10x v2)

### ISSUE THREAD

**Issue by jychien** [chanzuckerberg/corpora-data-portal#197]
Run Optimus pipeline on **SingleCellLiverLandscape** and analyze differences between pBAM vs BAM results:

**Project Title**: Dissecting the human liver cellular landscape by single cell RNA-seq reveals novel intrahepatic monocyte/ macrophage populations
**Project URL**: https://data.humancellatlas.org/explore/projects/4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
**Donors**: P2TLH_liver and P3TLH_liver

- [x] Place subset of BAM files and expression matrix into gcp bucket
- [x] Check pBAM files to make sure alignments are as expected
- [ ] Process dataset through pipelines w/ pFASTQ as input
- [ ] Compare pBAM outputs with HCA output, and each with findings from the published results

**Comment by jychien** [comment]
**BAM FILES AND EXPRESSION MATRIX:**
- Obtained relevant bam files, fastqs, and subsetted expression matrix and placed them in gs://pbam_singlecell/input_data/10x_v2_liver/
&nbsp;  

**CHECK pBAM FILES:**

**Documentation**: https://docs.google.com/presentation/d/1Ih9fEqp9P5CT4Y3UlyqswZx4h_mBS-mP0Q4FgOh1J6I/edit?usp=sharing

**Task**: Spot checked alignments with insertion (I), soft clipping (S), deletion (D), MD:Z flag (SNPs), or complex CIGAR strings in pBAM file. Used samtools and IGV viewer to visualize alignment.

**Result**: Gamze produced a sample pbam file in gs://pbam_singlecell/pBAMs/10x_v2/v1. The start location of an alignment needs to be changed for subset of alignments when converted to pBAM. This was corrected and checked in gs://pbam_singlecell/pBAMs/10x_v2/v2
