### ISSUE TITLE
cellxgene hosted multi-dataset/multi-user

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#30]
Create a version of cellxgene which is capable of:
* serving multiple public, read-only datasets from S3
* serving to multiple users
* can be hosted on AWS
* has all current (as of v0.14) cellxgene non-experimental _read-only_ features (ie, contains diffexp, but does not contain user-created annotations).

Also create preliminary script which can create test datasets for serving, i,e "CXG" objects built on top of tiledb.

Tasks:
- [x] refactor cellxgene for multiple backends  #57
- [x] Backend (server) which an serve CXG/tiledb data  #31
- [x] Deployable as a dev instance to AWS EB #38
- [x] CXG/tiledb schema defined and available in draft project docs  #36
- [x] H5AD to CXG converter - stand-alone conversion of H5AD to CXG for general use & testing  #37
- [ ] WSGI app config system  #203

**Comment by ambrosejcarr** [comment]
Estimate: small.
