### ISSUE TITLE
Enable Read Projects

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/corpora-data-portal#394]
Implement the endpoints required for reading Projects and Datasets:
- [x] GET `/submission/{project_id}`: read EDIT project
- [x] GET `/project/{project_id}`: read LIVE project
- [x] GET `/project/`: get a list of projects

**Comment by Bento007** [comment]
Complete
