### ISSUE TITLE
cellxgene production DCP application deployment

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#43]
Create an initial version of the Production (M3) deployment of the cellxgene application.   This includes:
* production deployment scripts to AWS
* autoscaling of server resources
* usage tracking/metrics
* integration with user auth (registration) system 
* data access logging
* configuration system appropriate for hosted
* HTTPS/certificate

Tasks:
- [ ] usage tracking & metrics using google analytics
- [ ] production deployment tools/scripts to Elastic Beanstalk
- [ ] autoscale production web servers
- [ ] user auth integration - depends on user auth system
- [ ] user access logging - depends on logging framework
- [ ] configuration system
- [ ] DNS name
- [ ] certificate
- [ ] HTTPS
