### ISSUE TITLE
The browser can be viewed from a mobile application

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#59]
## Story
_As a user of the HCA, I want to be able use the browser on my mobile device so that I can show others my project or find download links to share with collaborators_

## Acceptance Criteria:
- [ ] create menu in place of the laptop screen's top bar. 
- [ ] create list-of-projects page for mobile
- [ ] create project page with both project info + list of categories for mobile
- [ ] create file selection modal for mobile
- [ ] create resulting list of URLs for download for mobile
- [ ] browser is usable on a mobile device.

**Comment by ambrosejcarr** [comment]
Estimates:
3 days FE
2 days Design.
