### ISSUE TITLE
Browser tracking and metrics

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#64]
## Background

We would like to be able to evaluate how users are finding and interacting with our service. Specifically, we would like information on: 
- how are users finding our browser? 
- what devices are they using to navigate the browser? 
- what are common paths users take through the browser?
- are there parts of the browser that are under-utilized that we should determine if they are hard to find or low value? 

## Acceptance Criteria

- [ ] AC: Learn about analytics services. 
- [ ] AC: Create a report summarizing popular options and what they would enable us to learn about user interactions with our browser. 
- [ ] AC: Make a recommendation. 
- [ ] AC: Validate with the CZI Security and Infrastructure group that we can use the recommended service.
