### ISSUE TITLE
CXG can be launched from data derived from a published artifact. 

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/corpora-data-portal#69]
Create data conversion process and scripts necessary to convert an Artifact instance to a CXG, suitable for serving to hosted cellxgene.   Manual deployment of the CXG is assumed - this epic does not include automated ETL/publication process or data lifecycle management.

Dependency:  the Artifact spec fulfills cellxgene requirements.

Tasks:
- [ ] define which metadata to import to to CXG  #121
- [x] Loom to CXG converter - stand-alone conversion of Loom to CXG for general use & testing.  #37
- [ ] Artifact to CXG converter - DCP-specific stand-alone Artifact to CXG converter (it is likely that this will build upon the Loom converter).   #40
- [ ] Data generation documentation - recipes to help Wranglers generate CXGs. May simply end up as input to Wrangler Tools documentation.   #39
- [x] CXG schema - draft specification of CXG format & constraints.  #36

**Comment by bkmartinjr** [comment]
Loom conversion can currently be performed with two-step process:
1. `cellxgene prepare f.loom` -> f.h5ad
2. `python cxgtool.py f.h5ad` -> f.cxg
